name: june22
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - click
  - sphinx=2.4.4
  - jupyter
  - jupytext
  - jb_test
  - sqlalchemy
  - pip
  - pip:
    - click_log
    - click_completion
    - jupyter-sphinx
    - pyyaml
    - docutils>=0.15
    - myst-parser~=0.8
    - sphinx<3
    - click
    - setuptools
    - nbformat
    - nbconvert
    - nbclient
    - sphinx_togglebutton
    - sphinx-copybutton
    - sphinxcontrib-bibtex
    - sphinx_book_theme~=0.0


