name: june21
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - click
  - sphinx=2.4.4
  - jupyter
  - pip
  - pip:
    - click_log
    - click_completion
    - git+https://github.com/jupyter/jupyter-sphinx.git
    - git+https://github.com/phaustin/MyST-NB.git
    - git+https://github.com/phaustin/jupyter-cache
    - https://clouds.eos.ubc.ca/~phil/docs/wheels/jupyter_cache-0.2.2-py3-none-any.whl
    - https://clouds.eos.ubc.ca/~phil/docs/wheels/jupyter_book-0.7.1.dev0-py3-none-any.whl
    - git+https://github.com/mwouts/jupytext.git
