name: nested
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - click
  - pre-commit
  - libsass
  - pydata-sphinx-theme
  - nbclient
  - sqlalchemy
  - nbdime
  - git
  - pip:
    - sphinxcontrib-bibtex
    - sphinx-copybutton
    - sphinx-togglebutton
    - git+https://github.com/executablebooks/myst-parser.git
    - click_log
    - click_completion
    - git+https://github.com/jupyter/jupyter-sphinx.git
    - git+https://github.com/mwouts/jupytext.git
